In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("50_Startups.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [6]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
data.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [8]:
# Sperate my data as features and label

features = data.iloc[:,[0,1,2,3]].values
label = data.iloc[:,[4]]

In [9]:
#Deal with categorical data

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
dummyState = ohe.fit_transform(features[:,[3]])

In [10]:
dummyState

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [11]:
#FinalFeature Set

finalFeatureSet = np.concatenate( (dummyState, features[:,[0,1,2]]) , axis = 1)
finalFeatureSet

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [12]:
# Create train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(finalFeatureSet,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=3)

In [13]:
X_train

array([[0.0, 1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [0.0, 1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [1.0, 0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1.0, 0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1.0, 0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [0.0, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53

In [13]:
# Apply Regression to create the model
# Model Convergence ---- Training model using algo

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [14]:
# Guidelines
#
# Model Convergence Exploration Phase - Goal is to get those models that fit our criteria of Generalization
#

#
# Universal Law: Statistics says every algorithm related to data and model
# convergence gets affected based on the Sample and its representation (Based on how sampling is done)
#

# EarlyStopping --- Stopping the training as soon as our criteria is achieved

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

CL = 0.99

for randomValue in range(1,100):
  X_train,X_test,y_train,y_test = train_test_split(finalFeatureSet,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=randomValue)
  model = LinearRegression()
  model.fit(X_train,y_train)

  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)

  if testScore > trainScore and testScore >= CL:
    print("TestScore {} TrainScore {} For Given Random State Value {}".format(testScore,trainScore,randomValue))

TestScore 0.990110511339805 TrainScore 0.9385918220043519 For Given Random State Value 10


In [15]:
# Guideline
#
# Check the quality of the model
#
# 1. Ensure the trained/converged model is a generalized model (Generalization)
#
#  testScore > trainScore and testScore >= CL
#
# Ensuring our model satisfies the SL criteria
# Assume SL = 0.01 ; CL = 0.99
#

In [16]:
X_train,X_test,y_train,y_test = train_test_split(finalFeatureSet,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=10)

In [17]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [18]:
#Sklearn offers score function
# For Regression --- to calc the score the formula used is R2

CL=0.99

trainScore = model.score(X_train,y_train)
testScore = model.score(X_test,y_test)

if testScore > trainScore and testScore >= CL:
  print("Approve Model")
else:
  print("Alert!  Improve the Model !")

print("Train Score is {} and TestScore is {}".format(trainScore,testScore))

Approve Model
Train Score is 0.9385918220043519 and TestScore is 0.990110511339805


In [20]:
# Deploy Code

rdSpend = float(input("Enter RD Spend: "))
admSpend = float(input("Enter Admin Spend: "))
markSpend = float(input("Enter Marketing Spend: "))
state = input("Enter State: ")

if state in ohe.categories_[0]:
  encodedState = ohe.transform(np.array([[state]]))
  finalFeature = np.concatenate( (encodedState,np.array([[rdSpend,admSpend,markSpend]])) , axis = 1)
  predictProfit = model.predict(finalFeature)[0][0]
  print("Predicted profit is $ {}".format(predictProfit))
else:
  print("Given state {} is not supported by the model ".format(state))

Enter RD Spend: 35645
Enter Admin Spend: 477
Enter Marketing Spend: 35466
Enter State: California
Predicted profit is $ 79611.29584892953


In [21]:
# Exporting relevant object
import pickle

pickle.dump(model , open("ProfitPredictor.pkl","wb"))
pickle.dump(ohe, open("StateEncoderDecoder.pkl","wb"))

In [28]:
with open('StateEncoderDecoder.pkl', 'rb') as file:
    my_list = pickle.load(file)

my_list

OneHotEncoder(sparse=False, sparse_output=False)

In [22]:
encodedState


array([[1., 0., 0.]])

In [23]:
# Using Model Object we can extract the coeff and intercept

model.coef_

array([[ 8.41023126e+01,  6.95447747e+02, -7.79550060e+02,
         8.05859453e-01, -1.79706621e-02,  2.28153524e-02]])

In [24]:
model.intercept_

array([50001.73604084])

In [25]:
#
# profit = 50001.73604086 + 8.41023126e+01 (California) + 6.95447747e+02(Florida) -7.79550060e+02 (NY) + 8.05859453e-01 (rdSpend)
#          - 1.79706621e-02 (admSpend) + 2.28153524e-02 (markSpend)
#